baseurl = "http://aknowledge.xyz/"
languageCode = "en-us"
title = "AKnowledge"
theme = "future-imperfect"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = ""
googleAnalytics = "UA-78082886-1"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Dumping ground for tech, code, travel, and more"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "AKnowledge"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""
    # Load minified files instead of the non minified files. The variable
    # is an array so that you can load multiple min files if necessary
    # Note: There are other ways to approach minification
    # This is just an additional option if you wish to use this
#    minifiedFilesCSS     = ["/css/main.min.css"]
#    minifiedFilesJS      = ["/js/main.min.js"]

    # Isso Params
    issoApiUrl = "//comments.aknowledge.xyz/"
    issoClientUrl = "//comments.aknowledge.xyz/js/embed.min.js"
    issoRequireEmail = "true"

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "AKnowledge"

    paragraph = "A dumping ground for all things technology, travel, music, and more."

    about     = "Aaron Kanter is a generalist developer, musician, and traveler based out of San Francisco"

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/main/logo.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = false
    imperfect = true
    width     = ""
    alt       = "AK"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "Blog"
    url = "/blog"
    identifier = "fa fa-newspaper-o"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    github          = "akanter"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "aaron-kanter-a5b04837"
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = "alkanter"
    facebook        = "akanter"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = ""
    email           = ""

[taxonomies]
tag = "tags"
category = "categories"
series = "series"